import type { VBIDimension, VBIMeasure } from '@visactor/vbi'
import type { StreamLabels } from 'src/config/labels'

type DimensionEncoding = NonNullable<VBIDimension['encoding']>
type MeasureEncoding = NonNullable<VBIMeasure['encoding']>

const dimensionTitles: Record<StreamLabels['locale'], Record<DimensionEncoding, string>> = {
  'zh-CN': {
    angle: '角度',
    color: '颜色',
    column: '列',
    detail: '明细',
    hierarchy: '层级',
    label: '标签',
    player: '播放',
    row: '行',
    tooltip: '提示',
    xAxis: 'X 轴 / 时间',
    yAxis: 'Y 轴',
  },
  'en-US': {
    angle: 'Angle',
    color: 'Color',
    column: 'Column',
    detail: 'Detail',
    hierarchy: 'Hierarchy',
    label: 'Label',
    player: 'Player',
    row: 'Row',
    tooltip: 'Tooltip',
    xAxis: 'X / Time',
    yAxis: 'Y',
  },
  'ja-JP': {
    angle: '角度',
    color: '色',
    column: '列',
    detail: '詳細',
    hierarchy: '階層',
    label: 'ラベル',
    player: '再生',
    row: '行',
    tooltip: 'ツールチップ',
    xAxis: 'X / 時間',
    yAxis: 'Y',
  },
  'de-DE': {
    angle: 'Winkel',
    color: 'Farbe',
    column: 'Spalte',
    detail: 'Detail',
    hierarchy: 'Hierarchie',
    label: 'Beschriftung',
    player: 'Player',
    row: 'Zeile',
    tooltip: 'Tooltip',
    xAxis: 'X / Zeit',
    yAxis: 'Y',
  },
  'id-ID': {
    angle: 'Sudut',
    color: 'Warna',
    column: 'Kolom',
    detail: 'Detail',
    hierarchy: 'Hierarki',
    label: 'Label',
    player: 'Pemutar',
    row: 'Baris',
    tooltip: 'Tooltip',
    xAxis: 'X / Waktu',
    yAxis: 'Y',
  },
  'fr-FR': {
    angle: 'Angle',
    color: 'Couleur',
    column: 'Colonne',
    detail: 'Détail',
    hierarchy: 'Hiérarchie',
    label: 'Libellé',
    player: 'Lecture',
    row: 'Ligne',
    tooltip: 'Info-bulle',
    xAxis: 'X / Temps',
    yAxis: 'Y',
  },
  'ko-KR': {
    angle: '각도',
    color: '색상',
    column: '열',
    detail: '상세',
    hierarchy: '계층',
    label: '레이블',
    player: '재생',
    row: '행',
    tooltip: '툴팁',
    xAxis: 'X / 시간',
    yAxis: 'Y',
  },
  'vi-VN': {
    angle: 'Góc',
    color: 'Màu',
    column: 'Cột',
    detail: 'Chi tiết',
    hierarchy: 'Phân cấp',
    label: 'Nhãn',
    player: 'Phát',
    row: 'Hàng',
    tooltip: 'Chú giải',
    xAxis: 'X / Thời gian',
    yAxis: 'Y',
  },
}

const measureTitles: Record<StreamLabels['locale'], Record<MeasureEncoding, string>> = {
  'zh-CN': {
    angle: '角度',
    color: '颜色',
    column: '列',
    detail: '明细',
    label: '标签',
    max: '最大值',
    median: '中位数',
    min: '最小值',
    outliers: '异常值',
    primaryYAxis: '主 Y 轴',
    q1: 'Q1',
    q3: 'Q3',
    radius: '半径',
    secondaryYAxis: '副 Y 轴',
    size: '大小',
    tooltip: '提示',
    value: '值',
    x0: 'X0',
    x1: 'X1',
    xAxis: 'X 轴',
    yAxis: 'Y 轴',
  },
  'en-US': {
    angle: 'Angle',
    color: 'Color',
    column: 'Column',
    detail: 'Detail',
    label: 'Label',
    max: 'Max',
    median: 'Median',
    min: 'Min',
    outliers: 'Outliers',
    primaryYAxis: 'Primary Y',
    q1: 'Q1',
    q3: 'Q3',
    radius: 'Radius',
    secondaryYAxis: 'Secondary Y',
    size: 'Size',
    tooltip: 'Tooltip',
    value: 'Value',
    x0: 'X0',
    x1: 'X1',
    xAxis: 'X',
    yAxis: 'Y',
  },
  'ja-JP': {
    angle: '角度',
    color: '色',
    column: '列',
    detail: '詳細',
    label: 'ラベル',
    max: '最大値',
    median: '中央値',
    min: '最小値',
    outliers: '外れ値',
    primaryYAxis: '主 Y 軸',
    q1: 'Q1',
    q3: 'Q3',
    radius: '半径',
    secondaryYAxis: '副 Y 軸',
    size: 'サイズ',
    tooltip: 'ツールチップ',
    value: '値',
    x0: 'X0',
    x1: 'X1',
    xAxis: 'X',
    yAxis: 'Y',
  },
  'de-DE': {
    angle: 'Winkel',
    color: 'Farbe',
    column: 'Spalte',
    detail: 'Detail',
    label: 'Beschriftung',
    max: 'Max.',
    median: 'Median',
    min: 'Min.',
    outliers: 'Ausreißer',
    primaryYAxis: 'Primäre Y-Achse',
    q1: 'Q1',
    q3: 'Q3',
    radius: 'Radius',
    secondaryYAxis: 'Sekundäre Y-Achse',
    size: 'Größe',
    tooltip: 'Tooltip',
    value: 'Wert',
    x0: 'X0',
    x1: 'X1',
    xAxis: 'X',
    yAxis: 'Y',
  },
  'id-ID': {
    angle: 'Sudut',
    color: 'Warna',
    column: 'Kolom',
    detail: 'Detail',
    label: 'Label',
    max: 'Maks',
    median: 'Median',
    min: 'Min',
    outliers: 'Pencilan',
    primaryYAxis: 'Y utama',
    q1: 'Q1',
    q3: 'Q3',
    radius: 'Radius',
    secondaryYAxis: 'Y sekunder',
    size: 'Ukuran',
    tooltip: 'Tooltip',
    value: 'Nilai',
    x0: 'X0',
    x1: 'X1',
    xAxis: 'X',
    yAxis: 'Y',
  },
  'fr-FR': {
    angle: 'Angle',
    color: 'Couleur',
    column: 'Colonne',
    detail: 'Détail',
    label: 'Libellé',
    max: 'Max.',
    median: 'Médiane',
    min: 'Min.',
    outliers: 'Valeurs aberrantes',
    primaryYAxis: 'Axe Y principal',
    q1: 'Q1',
    q3: 'Q3',
    radius: 'Rayon',
    secondaryYAxis: 'Axe Y secondaire',
    size: 'Taille',
    tooltip: 'Info-bulle',
    value: 'Valeur',
    x0: 'X0',
    x1: 'X1',
    xAxis: 'X',
    yAxis: 'Y',
  },
  'ko-KR': {
    angle: '각도',
    color: '색상',
    column: '열',
    detail: '상세',
    label: '레이블',
    max: '최대',
    median: '중앙값',
    min: '최소',
    outliers: '이상값',
    primaryYAxis: '주 Y축',
    q1: 'Q1',
    q3: 'Q3',
    radius: '반경',
    secondaryYAxis: '보조 Y축',
    size: '크기',
    tooltip: '툴팁',
    value: '값',
    x0: 'X0',
    x1: 'X1',
    xAxis: 'X',
    yAxis: 'Y',
  },
  'vi-VN': {
    angle: 'Góc',
    color: 'Màu',
    column: 'Cột',
    detail: 'Chi tiết',
    label: 'Nhãn',
    max: 'Tối đa',
    median: 'Trung vị',
    min: 'Tối thiểu',
    outliers: 'Ngoại lệ',
    primaryYAxis: 'Trục Y chính',
    q1: 'Q1',
    q3: 'Q3',
    radius: 'Bán kính',
    secondaryYAxis: 'Trục Y phụ',
    size: 'Kích thước',
    tooltip: 'Chú giải',
    value: 'Giá trị',
    x0: 'X0',
    x1: 'X1',
    xAxis: 'X',
    yAxis: 'Y',
  },
}

export const getEncodingTitle = (
  labels: StreamLabels,
  slot: { dimensionEncoding?: DimensionEncoding; measureEncoding?: MeasureEncoding },
) => {
  if (slot.dimensionEncoding) return dimensionTitles[labels.locale][slot.dimensionEncoding]
  if (slot.measureEncoding) return measureTitles[labels.locale][slot.measureEncoding]
  return ''
}
