import { createVBI, VBIDashboardBuilder, type VBIDashboardBuilderOptions } from '@visactor/vbi'
import { rs } from '@rstest/core'
import * as Y from 'yjs'

const docs: Y.Doc[] = []
const createDashboard = (options?: VBIDashboardBuilderOptions) => {
  const vbi = createVBI()
  const builder = vbi.dashboard.create(vbi.dashboard.createEmpty(), options)
  docs.push(builder.doc)
  return builder
}
const clone = (builder: VBIDashboardBuilder) => {
  const doc = new Y.Doc()
  Y.applyUpdate(doc, builder.encodeStateAsUpdate())
  docs.push(doc)
  return new VBIDashboardBuilder(doc)
}
const position = { x: 0, y: 0, w: 4, h: 3 }
const addChart = (builder: VBIDashboardBuilder, title = 'Sales') => {
  builder.chart.add((widget) => widget.setTitle(title).setLayouts({ lg: position, md: position }))
  return builder.chart.findAll().at(-1)!.getId()
}

afterEach(() => {
  docs.splice(0).forEach((doc) => doc.destroy())
})

test('captures each chart insertion, update and removal atomically with all breakpoint layouts', () => {
  const builder = createDashboard()
  const initial = builder.build()
  expect(builder.undoManager.canUndo()).toBe(false)
  expect(builder.undoManager.undo()).toBe(false)
  expect(builder.undoManager.redo()).toBe(false)
  const updates = rs.fn()
  builder.doc.on('update', updates)
  const id = addChart(builder)
  const added = builder.build()
  expect(updates).toHaveBeenCalledTimes(1)
  expect(builder.undoManager.undo()).toBe(true)
  expect(builder.build()).toEqual(initial)
  expect(builder.undoManager.redo()).toBe(true)
  expect(builder.build()).toEqual(added)
  builder.chart.update(id, (widget) => widget.setTitle('Revenue').setLayouts({ lg: { ...position, x: 4 } }))
  const updated = builder.build()
  expect(updated.layout.lg![0].id).toBe(added.layout.lg![0].id)
  builder.undoManager.undo()
  expect(builder.build()).toEqual(added)
  builder.undoManager.redo()
  expect(builder.build()).toEqual(updated)
  builder.chart.remove(id)
  expect(builder.build().layout.lg).toEqual([])
  expect(builder.build().layout.md).toEqual([])
  builder.undoManager.undo()
  expect(builder.build()).toEqual(updated)
  builder.undoManager.redo()
  expect(builder.isEmpty()).toBe(true)
})

test('restores insight nodes and layouts and starts a new history branch after an edit', () => {
  const builder = createDashboard()
  builder.insight.add((widget) => widget.setTitle('Notes').setLayouts({ lg: position }))
  const added = builder.build()
  const id = added.widgets[0].id
  builder.insight.update(id, (widget) => widget.setDescription('Updated'))
  builder.undoManager.undo()
  expect(builder.build()).toEqual(added)
  builder.insight.remove(id)
  expect(builder.undoManager.canRedo()).toBe(false)
  builder.undoManager.undo()
  expect(builder.build()).toEqual(added)
  builder.undoManager.undo()
  expect(builder.isEmpty()).toBe(true)
  builder.undoManager.redo()
  expect(builder.build()).toEqual(added)
})

test('groups widget and theme edits into one explicit transaction and tracks direct nested mutations', () => {
  const builder = createDashboard()
  builder.transact(() => {
    addChart(builder)
    builder.insight.add((widget) => widget.setLayouts({ lg: position }))
    builder.theme.setTheme('dark')
  })
  const edited = builder.build()
  builder.undoManager.undo()
  expect(builder.isEmpty()).toBe(true)
  expect(builder.theme.getTheme()).toBe('light')
  builder.undoManager.redo()
  expect(builder.build()).toEqual(edited)
  const widget = builder.chart.findAll()[0]
  widget.setTitle('Direct change')
  builder.undoManager.undo()
  expect(builder.chart.get(widget.getId())?.toJSON().title).toBe('Sales')
})

test('excludes remote updates without an origin and synchronizes local undo/redo as ordinary Yjs updates', () => {
  const first = createDashboard()
  const replica = clone(first)
  addChart(first)
  replica.applyUpdate(first.encodeStateAsUpdate())
  expect(replica.build()).toEqual(first.build())
  expect(replica.undoManager.canUndo()).toBe(false)
  first.undoManager.undo()
  replica.applyUpdate(first.encodeStateAsUpdate(Y.encodeStateVector(replica.doc)))
  expect(replica.isEmpty()).toBe(true)
  first.undoManager.redo()
  replica.applyUpdate(first.encodeStateAsUpdate(), 'provider')
  expect(replica.build()).toEqual(first.build())
  expect(replica.undoManager.canUndo()).toBe(false)
  first.undoManager.undo()
  replica.theme.setTheme('dark')
  first.applyUpdate(replica.encodeStateAsUpdate())
  expect(first.undoManager.canRedo()).toBe(true)
  first.undoManager.redo()
  expect(first.theme.getTheme()).toBe('dark')
})

test('undoes local layout fields while retaining concurrent peer changes to the same and other widgets', () => {
  const first = createDashboard()
  const a = addChart(first, 'A')
  const b = addChart(first, 'B')
  first.undoManager.clear()
  const replica = clone(first)
  first.chart.update(a, (widget) => widget.setTitle('Local').setLayouts({ lg: { ...position, x: 4 } }))
  replica.chart.update(a, (widget) => widget.setDescription('Peer').setLayouts({ lg: { ...position, y: 3 } }))
  replica.chart.update(b, (widget) => widget.setLayouts({ lg: { ...position, w: 6 } }))
  first.applyUpdate(replica.encodeStateAsUpdate())
  replica.applyUpdate(first.encodeStateAsUpdate())
  expect(first.build()).toEqual(replica.build())
  expect(first.build().layout.lg!.find((item) => item.widgetId === a)).toMatchObject({ x: 4, y: 3 })
  first.undoManager.undo()
  expect(first.chart.get(a)?.toJSON()).toMatchObject({ title: 'A', description: 'Peer' })
  expect(first.build().layout.lg!.find((item) => item.widgetId === a)).toMatchObject({ x: 0, y: 3 })
  expect(first.build().layout.lg!.find((item) => item.widgetId === b)).toMatchObject({ w: 6 })
  replica.applyUpdate(first.encodeStateAsUpdate())
  expect(first.build()).toEqual(replica.build())
})

test('keeps peer insertions when undoing a local insertion and never overwrites a later remote map value', () => {
  const first = createDashboard()
  const replica = clone(first)
  const a = addChart(first, 'Local')
  addChart(replica, 'Peer')
  first.applyUpdate(replica.encodeStateAsUpdate())
  first.undoManager.undo()
  expect(first.build().widgets.map((widget) => widget.title)).toEqual(['Peer'])
  expect(first.build().layout.lg).toHaveLength(1)
  first.undoManager.redo()
  first.undoManager.clear()
  first.chart.update(a, (widget) => widget.setTitle('Local rename'))
  replica.applyUpdate(first.encodeStateAsUpdate())
  replica.chart.update(a, (widget) => widget.setTitle('Peer rename'))
  first.applyUpdate(replica.encodeStateAsUpdate())
  expect(first.undoManager.undo()).toBe(false)
  expect(first.chart.get(a)?.toJSON().title).toBe('Peer rename')
})

test('configures origin tracking, capture boundaries, selective clearing, observers and disposal', () => {
  const origin = {}
  const origins = new Set([origin])
  const builder = createDashboard({ undoManager: { captureTimeout: 500, trackedOrigins: origins } })
  expect(origins.size).toBe(1)
  const states: boolean[][] = []
  const unsubscribe = builder.undoManager.observe(() =>
    states.push([builder.undoManager.canUndo(), builder.undoManager.canRedo()]),
  )
  builder.theme.setTheme('dark')
  expect(builder.undoManager.canUndo()).toBe(false)
  builder.transact(() => builder.theme.setTheme('light'), origin)
  builder.transact(() => builder.theme.setTheme('dark'), origin)
  expect(states).toHaveLength(2)
  builder.undoManager.stopCapturing()
  builder.transact(() => builder.theme.setTheme('light'), origin)
  builder.undoManager.undo()
  expect(builder.theme.getTheme()).toBe('dark')
  builder.undoManager.clear(true, false)
  expect(builder.undoManager.canUndo()).toBe(false)
  expect(builder.undoManager.canRedo()).toBe(true)
  builder.undoManager.clear(false, true)
  expect(builder.undoManager.canRedo()).toBe(false)
  unsubscribe()
  const count = states.length
  builder.undoManager.removeTrackedOrigin(origin)
  builder.transact(() => builder.theme.setTheme('light'), origin)
  expect(builder.undoManager.canUndo()).toBe(false)
  builder.undoManager.addTrackedOrigin(null)
  builder.theme.setTheme('dark')
  expect(builder.undoManager.canUndo()).toBe(true)
  expect(states).toHaveLength(count)
  builder.undoManager.clear()
  builder.undoManager.destroy()
  builder.theme.setTheme('light')
  expect(builder.undoManager.canUndo()).toBe(false)
})

test('keeps referenced resource documents outside dashboard history', () => {
  const vbi = createVBI()
  const chart = vbi.chart.create(vbi.chart.createEmpty('demo'))
  const insight = vbi.insight.create(vbi.insight.createEmpty())
  const dashboard = vbi.dashboard.create(vbi.dashboard.createEmpty())
  docs.push(dashboard.doc, chart.doc, insight.doc)
  dashboard.transact(() => {
    dashboard.chart.add((widget) => widget.setChart(chart).setLayouts({ lg: position }))
    dashboard.insight.add((widget) => widget.setInsightId(insight).setLayouts({ lg: position }))
  })
  const snapshot = dashboard.build()
  chart.chartType.changeChartType('bar')
  insight.setContent('Resource content')
  dashboard.undoManager.undo()
  expect(dashboard.isEmpty()).toBe(true)
  expect(chart.build().chartType).toBe('bar')
  expect(insight.build().content).toBe('Resource content')
  dashboard.undoManager.redo()
  expect(dashboard.build()).toEqual(snapshot)
  const restored = vbi.dashboard.create(snapshot)
  docs.push(restored.doc)
  expect(restored.undoManager.canUndo()).toBe(false)
  expect(restored.build()).toEqual(snapshot)
})

test('normalizes optional persisted layouts before tracking history and preserves optional layout flags on undo', () => {
  const vbi = createVBI()
  const snapshot = vbi.dashboard.createEmpty()
  const builder = vbi.dashboard.create({ ...snapshot, layout: { ...snapshot.layout, sm: undefined } })
  docs.push(builder.doc)
  expect(builder.undoManager.canUndo()).toBe(false)
  expect(builder.build().layout.sm).toEqual([])
  const id = addChart(builder)
  builder.chart.update(id, (widget) => widget.setLayouts({ lg: { ...position, static: true } }))
  expect(builder.build().layout.lg![0].static).toBe(true)
  builder.chart.update(id, (widget) => widget.setLayouts({ lg: position }))
  expect(builder.build().layout.lg![0].static).toBeUndefined()
  builder.undoManager.undo()
  expect(builder.build().layout.lg![0].static).toBe(true)
})
