import type { ProfessionalLocale } from 'src/constants/builder'

const zh = {
  addField: '添加字段',
  chartType: '图表类型',
  config: '配置',
  configPanel: '配置面板',
  dataSource: '数据字段',
  dimensions: '维度',
  dragHint: '拖到匹配的编码槽，蓝色插入线表示落点',
  dropHere: '拖到这里',
  dropUnavailable: '类型不匹配',
  emptyChart: '拖入字段开始配置图表',
  exitFullscreen: '退出全屏',
  fieldCollapse: '收起',
  fieldExpand: '展开全部',
  formatCnyWan: '¥符号(万)',
  formatNumber2: '数值 (2)',
  formatPercent1: '百分比 (1)',
  formatScientific3: '科学计数 (3)',
  formatUsdK: '$K (2)',
  fullscreen: '全屏',
  insertAt: '插入位置',
  languageChinese: '中',
  languageEnglish: 'EN',
  limit: '行数',
  loading: '正在渲染...',
  menuAggregate: '聚合',
  menuAutoFormat: '自动格式',
  menuDelete: '删除',
  menuFormat: '格式',
  menuRaw: '原始值',
  menuRename: '重命名',
  menuSort: '排序',
  menuSortAsc: '升序',
  menuSortClear: '不排序',
  menuSortDesc: '降序',
  metrics: '指标',
  search: '搜索字段',
  themeDark: '深色',
  themeLight: '浅色',
  toolbarRedo: '重做',
  toolbarUndo: '撤销',
  unmatchedFields: '未匹配字段',
}

const en: typeof zh = {
  addField: 'Add field',
  chartType: 'Chart type',
  config: 'Config',
  configPanel: 'Config panel',
  dataSource: 'Fields',
  dimensions: 'Dimensions',
  dragHint: 'Drop on a matching encoding slot. The blue line marks the index.',
  dropHere: 'Drop here',
  dropUnavailable: 'Wrong field type',
  emptyChart: 'Drop fields to configure the chart',
  exitFullscreen: 'Exit fullscreen',
  fieldCollapse: 'Collapse',
  fieldExpand: 'Expand all',
  formatCnyWan: '¥Symbol(万)',
  formatNumber2: 'Number (2)',
  formatPercent1: 'Percent (1)',
  formatScientific3: 'Scientific (3)',
  formatUsdK: '$K (2)',
  fullscreen: 'Fullscreen',
  insertAt: 'Insert at',
  languageChinese: '中',
  languageEnglish: 'EN',
  limit: 'Rows',
  loading: 'Rendering...',
  menuAggregate: 'Aggregate',
  menuAutoFormat: 'Auto format',
  menuDelete: 'Delete',
  menuFormat: 'Format',
  menuRaw: 'Raw',
  menuRename: 'Rename',
  menuSort: 'Sort',
  menuSortAsc: 'Asc',
  menuSortClear: 'No sort',
  menuSortDesc: 'Desc',
  metrics: 'Metrics',
  search: 'Search fields',
  themeDark: 'Dark',
  themeLight: 'Light',
  toolbarRedo: 'Redo',
  toolbarUndo: 'Undo',
  unmatchedFields: 'Unmatched fields',
}

const ja: typeof zh = {
  addField: 'フィールドを追加',
  chartType: 'グラフタイプ',
  config: '設定',
  configPanel: '設定パネル',
  dataSource: 'フィールド',
  dimensions: 'ディメンション',
  dragHint: '対応するエンコーディングスロットにドロップします。青い線が挿入位置です。',
  dropHere: 'ここにドロップ',
  dropUnavailable: 'フィールドタイプが一致しません',
  emptyChart: 'フィールドをドロップしてグラフを設定',
  exitFullscreen: '全画面を終了',
  fieldCollapse: '折りたたむ',
  fieldExpand: 'すべて展開',
  formatCnyWan: '¥記号(万)',
  formatNumber2: '数値 (2)',
  formatPercent1: 'パーセント (1)',
  formatScientific3: '科学表記 (3)',
  formatUsdK: '$K (2)',
  fullscreen: '全画面',
  insertAt: '挿入位置',
  languageChinese: '中',
  languageEnglish: 'EN',
  limit: '行数',
  loading: 'レンダリング中...',
  menuAggregate: '集計',
  menuAutoFormat: '自動書式',
  menuDelete: '削除',
  menuFormat: '書式',
  menuRaw: '元の値',
  menuRename: '名前変更',
  menuSort: '並べ替え',
  menuSortAsc: '昇順',
  menuSortClear: '並べ替えなし',
  menuSortDesc: '降順',
  metrics: 'メトリクス',
  search: 'フィールドを検索',
  themeDark: 'ダーク',
  themeLight: 'ライト',
  toolbarRedo: 'やり直し',
  toolbarUndo: '元に戻す',
  unmatchedFields: '未一致のフィールド',
}

const de: typeof zh = {
  ...en,
  addField: 'Feld hinzufügen',
  chartType: 'Diagrammtyp',
  config: 'Konfiguration',
  configPanel: 'Konfigurationsbereich',
  dataSource: 'Felder',
  dimensions: 'Dimensionen',
  dragHint: 'Auf einen passenden Kodierungsslot ziehen. Die blaue Linie markiert die Position.',
  dropHere: 'Hier ablegen',
  dropUnavailable: 'Feldtyp passt nicht',
  emptyChart: 'Felder ablegen, um das Diagramm zu konfigurieren',
  exitFullscreen: 'Vollbild beenden',
  fieldCollapse: 'Einklappen',
  fieldExpand: 'Alle erweitern',
  fullscreen: 'Vollbild',
  insertAt: 'Einfügen bei',
  limit: 'Zeilen',
  loading: 'Wird gerendert...',
  menuAggregate: 'Aggregation',
  menuAutoFormat: 'Automatisches Format',
  menuDelete: 'Löschen',
  menuFormat: 'Format',
  menuRaw: 'Rohwert',
  menuRename: 'Umbenennen',
  menuSort: 'Sortieren',
  menuSortAsc: 'Aufsteigend',
  menuSortClear: 'Keine Sortierung',
  menuSortDesc: 'Absteigend',
  metrics: 'Kennzahlen',
  search: 'Felder suchen',
  themeDark: 'Dunkel',
  themeLight: 'Hell',
  toolbarRedo: 'Wiederholen',
  toolbarUndo: 'Rückgängig',
  unmatchedFields: 'Nicht zugeordnete Felder',
}

const id: typeof zh = {
  ...en,
  addField: 'Tambah field',
  chartType: 'Jenis grafik',
  config: 'Konfigurasi',
  configPanel: 'Panel konfigurasi',
  dataSource: 'Field',
  dimensions: 'Dimensi',
  dragHint: 'Letakkan pada slot encoding yang cocok. Garis biru menandai posisi sisip.',
  dropHere: 'Letakkan di sini',
  dropUnavailable: 'Jenis field tidak cocok',
  emptyChart: 'Letakkan field untuk mengonfigurasi grafik',
  exitFullscreen: 'Keluar layar penuh',
  fieldCollapse: 'Ciutkan',
  fieldExpand: 'Perluas semua',
  fullscreen: 'Layar penuh',
  insertAt: 'Sisipkan di',
  limit: 'Baris',
  loading: 'Merender...',
  menuAggregate: 'Agregasi',
  menuAutoFormat: 'Format otomatis',
  menuDelete: 'Hapus',
  menuFormat: 'Format',
  menuRaw: 'Mentah',
  menuRename: 'Ganti nama',
  menuSort: 'Urutkan',
  menuSortAsc: 'Naik',
  menuSortClear: 'Tanpa urutan',
  menuSortDesc: 'Turun',
  metrics: 'Metrik',
  search: 'Cari field',
  themeDark: 'Gelap',
  themeLight: 'Terang',
  toolbarRedo: 'Ulangi',
  toolbarUndo: 'Urungkan',
  unmatchedFields: 'Field tidak cocok',
}

const fr: typeof zh = {
  ...en,
  addField: 'Ajouter un champ',
  chartType: 'Type de graphique',
  config: 'Configuration',
  configPanel: 'Panneau de configuration',
  dataSource: 'Champs',
  dimensions: 'Dimensions',
  dragHint: 'Déposez sur un encodage compatible. La ligne bleue marque la position.',
  dropHere: 'Déposer ici',
  dropUnavailable: 'Type de champ incompatible',
  emptyChart: 'Déposez des champs pour configurer le graphique',
  exitFullscreen: 'Quitter le plein écran',
  fieldCollapse: 'Réduire',
  fieldExpand: 'Tout développer',
  fullscreen: 'Plein écran',
  insertAt: 'Insérer à',
  limit: 'Lignes',
  loading: 'Rendu en cours...',
  menuAggregate: 'Agrégation',
  menuAutoFormat: 'Format automatique',
  menuDelete: 'Supprimer',
  menuFormat: 'Format',
  menuRaw: 'Brut',
  menuRename: 'Renommer',
  menuSort: 'Trier',
  menuSortAsc: 'Croissant',
  menuSortClear: 'Aucun tri',
  menuSortDesc: 'Décroissant',
  metrics: 'Mesures',
  search: 'Rechercher des champs',
  themeDark: 'Sombre',
  themeLight: 'Clair',
  toolbarRedo: 'Rétablir',
  toolbarUndo: 'Annuler',
  unmatchedFields: 'Champs non associés',
}

const ko: typeof zh = {
  ...en,
  addField: '필드 추가',
  chartType: '차트 유형',
  config: '구성',
  configPanel: '구성 패널',
  dataSource: '필드',
  dimensions: '차원',
  dragHint: '일치하는 인코딩 슬롯에 놓으세요. 파란 선은 삽입 위치입니다.',
  dropHere: '여기에 놓기',
  dropUnavailable: '필드 유형이 맞지 않습니다',
  emptyChart: '필드를 놓아 차트를 구성',
  exitFullscreen: '전체 화면 종료',
  fieldCollapse: '접기',
  fieldExpand: '모두 펼치기',
  fullscreen: '전체 화면',
  insertAt: '삽입 위치',
  limit: '행',
  loading: '렌더링 중...',
  menuAggregate: '집계',
  menuAutoFormat: '자동 형식',
  menuDelete: '삭제',
  menuFormat: '형식',
  menuRaw: '원본',
  menuRename: '이름 변경',
  menuSort: '정렬',
  menuSortAsc: '오름차순',
  menuSortClear: '정렬 없음',
  menuSortDesc: '내림차순',
  metrics: '지표',
  search: '필드 검색',
  themeDark: '어둡게',
  themeLight: '밝게',
  toolbarRedo: '다시 실행',
  toolbarUndo: '실행 취소',
  unmatchedFields: '일치하지 않는 필드',
}

const vi: typeof zh = {
  ...en,
  addField: 'Thêm trường',
  chartType: 'Loại biểu đồ',
  config: 'Cấu hình',
  configPanel: 'Bảng cấu hình',
  dataSource: 'Trường',
  dimensions: 'Chiều dữ liệu',
  dragHint: 'Thả vào vị trí mã hóa phù hợp. Đường màu xanh đánh dấu vị trí chèn.',
  dropHere: 'Thả vào đây',
  dropUnavailable: 'Sai loại trường',
  emptyChart: 'Thả trường để cấu hình biểu đồ',
  exitFullscreen: 'Thoát toàn màn hình',
  fieldCollapse: 'Thu gọn',
  fieldExpand: 'Mở rộng tất cả',
  fullscreen: 'Toàn màn hình',
  insertAt: 'Chèn tại',
  limit: 'Hàng',
  loading: 'Đang kết xuất...',
  menuAggregate: 'Tổng hợp',
  menuAutoFormat: 'Định dạng tự động',
  menuDelete: 'Xóa',
  menuFormat: 'Định dạng',
  menuRaw: 'Gốc',
  menuRename: 'Đổi tên',
  menuSort: 'Sắp xếp',
  menuSortAsc: 'Tăng dần',
  menuSortClear: 'Không sắp xếp',
  menuSortDesc: 'Giảm dần',
  metrics: 'Chỉ số',
  search: 'Tìm trường',
  themeDark: 'Tối',
  themeLight: 'Sáng',
  toolbarRedo: 'Làm lại',
  toolbarUndo: 'Hoàn tác',
  unmatchedFields: 'Trường chưa khớp',
}

const messages: Record<ProfessionalLocale, typeof zh> = {
  'zh-CN': zh,
  'en-US': en,
  'ja-JP': ja,
  'de-DE': de,
  'id-ID': id,
  'fr-FR': fr,
  'ko-KR': ko,
  'vi-VN': vi,
}

export type ProfessionalLabels = ReturnType<typeof getLabels>

export const getLabels = (locale: ProfessionalLocale) => ({
  ...messages[locale],
  locale,
})
